#!/bin/bash
cd `dirname $0`
cd ..
rm -rf build/
mkdir build
cd build
# export http_proxy=socks5://127.0.0.1:1080
# export https_proxy=socks5://127.0.0.1:1080
cmake .. -DCROW_FEATURES="ssl;compression"
make -j12
cd ..
